apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-web
  namespace: argocd
spec:
  project: default
  source:
    path: ks8
    repoURL: 'https://github.com/dalaba-fouta/manifests'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true